// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import {Asset, Entry} from 'contentful'
import {Document} from '@contentful/rich-text-types'

export interface IContactPageFields {
  /** Top description */
  topDescription?: string | undefined

  /** Top description Mobile */
  topDescriptionMobile?: string | undefined

  /** Contact description */
  contactDescription?: string | undefined

  /** Iina description */
  iinaDescription?: string | undefined

  /** Unto description */
  untoDescription?: string | undefined

  /** Iina description Mobile */
  iinaDescriptionMobile?: string | undefined

  /** Unto description Mobile */
  untoDescriptionMobile?: string | undefined
}

/** All texts on contact page */

export interface IContactPage extends Entry<IContactPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'contactPage'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IHomepageFields {
  /** Header */
  header?: string | undefined

  /** Image */
  image?: Asset | undefined

  /** Description */
  description?: string | undefined
}

/** This is home page content */

export interface IHomepage extends Entry<IHomepageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'homepage'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IImageGalleryFields {
  /** Gallery name */
  galleryName: string

  /** layout type */
  layoutType?: ('full' | 'left' | 'right' | 'slider')[] | undefined

  /** images */
  images?: Asset[] | undefined
}

/** Different image show cases for projects */

export interface IImageGallery extends Entry<IImageGalleryFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'imageGallery'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IProjectFields {
  /** Name */
  name?: string | undefined

  /** main image */
  mainImage: Asset

  /** Project description */
  projectDescription?: string | undefined

  /** Year */
  year?: string | undefined

  /** Showcase url */
  galleryUrl: string

  /** Gallery on Homepage showcase */
  frontpageGallery: boolean

  /** order */
  order: number

  /** Collection type */
  collectionType: ('product' | 'set')[]

  /** Collection details */
  collectionDetails?: Document | undefined

  /** gallery reference */
  galleryReference?: IImageGallery[] | undefined
}

/** add each project here */

export interface IProject extends Entry<IProjectFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'project'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE =
  | 'contactPage'
  | 'homepage'
  | 'imageGallery'
  | 'project'

export type IEntry = IContactPage | IHomepage | IImageGallery | IProject

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
