// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import {Asset, Entry} from 'contentful'

export interface IContactPageFields {
  /** Top description */
  topDescription?: string | undefined

  /** Top description Mobile */
  topDescriptionMobile?: string | undefined

  /** Contact description */
  contactDescription?: string | undefined

  /** Iina description */
  iinaDescription?: string | undefined

  /** Unto description */
  untoDescription?: string | undefined

  /** Iina description Mobile */
  iinaDescriptionMobile?: string | undefined

  /** Unto description Mobile */
  untoDescriptionMobile?: string | undefined
}

/** All texts on contact page */

export interface IContactPage extends Entry<IContactPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'contactPage'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IImageGallery2Fields {
  /** name */
  name?: string | undefined

  /** Gallery Url */
  galleryUrl: string

  /** Gallery type */
  galleryType?: string | undefined

  /** gallery Images */
  galleryImages: Asset[]

  /** Gallery on Homepage */
  frontpageGallery: boolean

  /** order */
  order: number

  /** Team description */
  teamDescription?: string | undefined

  /** Project description */
  projectDescription?: string | undefined
}

/** add image galleries here */

export interface IImageGallery2 extends Entry<IImageGallery2Fields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'imageGallery2'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IKettunenRautioFields {
  /** Logo */
  logo?: Asset | undefined

  /** Header Desktop */
  description?: string | undefined

  /** Header */
  header?: string | undefined

  /** Header mobile */
  headermobile?: string | undefined

  /** Contact */
  contact?: string | undefined

  /** ContactUrl */
  contactUrl?: string | undefined

  /** SocialMediaLinks */
  socialMediaLinks?: string | undefined

  /** Copyright */
  copyright?: string | undefined

  /** galleries */
  galleries?: Entry<{[fieldId: string]: unknown}> | undefined
}

/** This is main content of the page */

export interface IKettunenRautio extends Entry<IKettunenRautioFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'kettunenRautio'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE = 'contactPage' | 'imageGallery2' | 'kettunenRautio'

export type IEntry = IContactPage | IImageGallery2 | IKettunenRautio

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
